
[theme] # You have to add this line

primaryColor = '#01A7DF' # Bright Orange

backgroundColor = '#013253' # White

secondaryBackgroundColor = '#FFFFFF' # Lighter Blue

textColor="#D0D0D0"

[server]

maxUploadSize = 20
